name: deploy website
on:
  push:
    branches:
      - main
jobs:
  deploy-backend:
    name: Deploy to Google App Engine
    steps:
      - uses: etereo-io/deploy-gae-action
        with:
          debug: true
          service_account:  ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_config_path: './packages/backend/app.yaml'

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-args: '--prod'
          working-directory: ./packages/frontend
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
