name: deploy website
on: [pull_request]
# on:
#   push:
#     branches:
#       - main
jobs:
  lint-build-test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test

  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-args: '--prod'
  #         working-directory: ./packages/frontend
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
