name: PR Checks
on: pull_request
jobs:
  deploy-backend:
    name: Deploy to Google App Engine
    steps:
      - uses: etereo-io/deploy-gae-action
        with:
          debug: true
          service_account:  ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_config_path: './packages/backend/app.yaml'

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run lint

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run build

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run test
