name: PR Checks
on: pull_request
jobs:
  deploy-backend:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: vijayp23/deploy-gae-action@1.0.1
        with:
          service-account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          config-files: './app.yml'
          # Optional
          service-version: 3                          #default value : ""
          delete-previous-versions: true              #default value : false
          service-name: ${{ secrets.SERVICE_NAME }}   #default value : default
          no-cache: false                             #default value : false
          debug: false                                #default value : false

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run lint

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run build

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - run: yarn install
  #     - run: yarn workspaces run test
